[project]
name = "eyecare"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.3.0",
    "playsound==1.2.2",
    "plyer>=2.1.0",
    "pyinstaller>=6.16.0",
    "pystray>=0.19.5",
]
